AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  A sample Lambda function deployed via a Devtron CI pipeline.

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  MyApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /hello
            Method: get